
import React from 'react';
import ReactDOM from 'react-dom';

let facts = [
  'If you have 3 quarters, 4 dimes, and 4 pennies, you have $1.19. You also have the largest amount of money in coins without being able to make change for a dollar.',
  'The numbers \'172\' can be found on the back of the U.S. $5 dollar bill in the bushes at the base of the Lincoln Memorial.',
  'President Kennedy was the fastest random speaker in the world with upwards of 350 words per minute.',
  'In the average lifetime, a person will walk the equivalent of 5 times around the equator.',
  'Odontophobia is the fear of teeth.',
  'The 57 on Heinz ketchup bottles represents the number of varieties of pickles the company once had.',
  'In the early days of the telephone, operators would pick up a call and use the phrase, "Well, are you there?". It wasn\'t until 1895 that someone suggested answering the phone with the phrase "number please?"',
  'The surface area of an average-sized brick is 79 cm squared.',
  'According to suicide statistics, Monday is the favored day for self-destruction.',
  'Cats sleep 16 to 18 hours per day.',
  'The most common name in the world is Mohammed.',
  'It is believed that Shakespeare was 46 around the time that the King James Version of the Bible was written. In Psalms 46, the 46th word from the first word is shake and the 46th word from the last word is spear.',
  'Karoke means "empty orchestra" in Japanese.',
  'The Eisenhower interstate system requires that one mile in every five must be straight. These straight sections are usable as airstrips in times of war or other emergencies.',
  'The first known contraceptive was crocodile dung, used by Egyptians in 2000 B.C.',
  'Rhode Island is the smallest state with the longest name. The official name, used on all state documents, is "Rhode Island and Providence Plantations."',
  'When you die your hair still grows for a couple of months.',
  'There are two credit cards for every person in the United States.',
  'Isaac Asimov is the only author to have a book in every Dewey-decimal category.',
  'The newspaper serving Frostbite Falls, Minnesota, the home of Rocky and Bullwinkle, is the Picayune Intellegence.',
  'It would take 11 Empire State Buildings, stacked one on top of the other, to measure the Gulf of Mexico at its deepest point.',
  'The first person selected as the Time Magazine Man of the Year - Charles Lindbergh in 1927.',
  'The most money ever paid for a cow in an auction was $1.3 million.',
  'It took Leo Tolstoy six years to write "War & Peace".',
  'The Neanderthal\'s brain was bigger than yours is.',
  'On the new hundred dollar bill the time on the clock tower of Independence Hall is 4:10.',
  'Each of the suits on a deck of cards represents the four major pillars of the economy in the middle ages: heart represented the Church, spades represented the military, clubs represented agriculture, and diamonds represented the merchant class.',
  'The names of the two stone lions in front of the New York Public Library are Patience and Fortitude. They were named by then-mayor Fiorello LaGuardia.',
  'The Main Library at Indiana University sinks over an inch every year because when it was built, engineers failed to take into account the weight of all the books that would occupy the building.',
  'The sound of E.T. walking was made by someone squishing her hands in jelly.',
  'Lucy and Linus (who where brother and sister) had another little brother named Rerun. (He sometimes played left-field on Charlie Brown\'s baseball team, [when he could find it!]).',
  'The pancreas produces Insulin.',
  '1 in 5,000 north Atlantic lobsters are born bright blue.',
  'There are 10 human body parts that are only 3 letters long (eye hip arm leg ear toe jaw rib lip gum).',
  'A skunk\'s smell can be detected by a human a mile away.',
  'The word "lethologica" describes the state of not being able to remember the word you want.',
  'The king of hearts is the only king without a moustache.',
  'Henry Ford produced the model T only in black because the black paint available at the time was the fastest to dry.',
  'Mario, of Super Mario Bros. fame, appeared in the 1981 arcade game, Donkey Kong. His original name was Jumpman, but was changed to Mario to honor the Nintendo of America\'s landlord, Mario Segali.',
  'The three best-known western names in China: Jesus Christ, Richard Nixon, and Elvis Presley.',
  'Every year about 98% of the atoms in your body are replaced.',
  'Elephants are the only mammals that can\'t jump.',
  'The international telephone dialing code for Antarctica is 672.',
  'World Tourist day is observed on September 27.',
  'Women are 37% more likely to go to a psychiatrist than men are.',
  'The human heart creates enough pressure to squirt blood 30 feet (9 m).',
  'Diet Coke was only invented in 1982.',
  'There are more than 1,700 references to gems and precious stones in the King James translation of the Bible.',
  'When snakes are born with two heads, they fight each other for food.',
  'American car horns beep in the tone of F.',
  'Turning a clock\'s hands counterclockwise while setting it is not necessarily harmful. It is only damaging when the timepiece contains a chiming mechanism.',
  'There are twice as many kangaroos in Australia as there are people. The kangaroo population is estimated at about 40 million.',
  'Police dogs are trained to react to commands in a foreign language; commonly German but more recently Hungarian.',
  'The Australian $5 to $100 notes are made of plastic.',
  '\'St. Stephen is the patron saint of bricklayers.',
  'The average person makes about 1,140 telephone calls each year.',
  '\'Stressed is Desserts spelled backwards.',
  'If you had enough water to fill one million goldfish bowls, you could fill an entire stadium.',
  'Mary Stuart became Queen of Scotland when she was only six days old.',
  'Charlie Brown\'s father was a barber.',
  'Flying from London to New York by Concord, due to the time zones crossed, you can arrive 2 hours before you leave.',
  'Dentists have recommended that a toothbrush be kept at least 6 feet (2 m) away from a toilet to avoid airborne particles resulting from the flush.',
  'You burn more calories sleeping than you do watching TV.',
  'A lion\'s roar can be heard from five miles away.',
  'The citrus soda 7-UP was created in 1929; "7" was selected because the original containers were 7 ounces. "UP" indicated the direction of the bubbles.',
  'Canadian researchers have found that Einstein\'s brain was 15% wider than normal.',
  'The average person spends about 2 years on the phone in a lifetime.',
  'The fist product to have a bar code was Wrigleys gum.',
  'The largest number of children born to one woman is recorded at 69. From 1725-1765, a Russian peasant woman gave birth to 16 sets of twins, 7 sets of triplets, and 4 sets of quadruplets.',
  'Beatrix Potter created the first of her legendary "Peter Rabbit" children\'s stories in 1902.',
  'In ancient Rome, it was considered a sign of leadership to be born with a crooked nose.',
  'The word "nerd" was first coined by Dr. Seuss in "If I Ran the Zoo."',
  'A 41-gun salute is the traditional salute to a royal birth in Great Britain.',
  'The bagpipe was originally made from the whole skin of a dead sheep.',
  'The roar that we hear when we place a seashell next to our ear is not the ocean, but rather the sound of blood surging through the veins in the ear. Any cup-shaped object placed over the ear produces the same effect.',
  'Revolvers cannot be silenced because of all the noisy gasses which escape the cylinder gap at the rear of the barrel.',
  'Liberace Museum has a mirror-plated Rolls Royce; jewel-encrusted capes, and the largest rhinestone in the world, weighing 59 pounds and almost a foot in diameter.',
  'A car that shifts manually gets 2 miles more per gallon of gas than a car with automatic shift.',
  'Cats can hear ultrasound.',
  'Dueling is legal in Paraguay as long as both parties are registered blood donors.',
  'The highest point in Pennsylvania is lower than the lowest point in Colorado.',
  'The United States has never lost a war in which mules were used.',
  'Children grow faster in the springtime.',
  'On average, there are 178 sesame seeds on each McDonalds BigMac bun.',
  'Paul Revere rode on a horse that belonged to Deacon Larkin.',
  'The Baby Ruth candy bar was actually named after Grover Cleveland\'s baby daughter, Ruth.',
  'Minus 40 degrees Celsius is exactly the same as minus 40 degrees Fahrenheit.',
  'Clans of long ago that wanted to get rid of unwanted people without killing them used to burn their houses down -- hence the expression "to get fired"',
  'Nobody knows who built the Taj Mahal. The names of the architects, masons, and designers that have come down to us have all proved to be latter-day inventions, and there is no evidence to indicate who the real creators were.',
  'Every human spent about half an hour as a single cell.',
  '7.5 million toothpicks can be created from a cord of wood.',
  'The plastic things on the end of shoelaces are called aglets.',
  'A 41-gun salute is the traditional salute to a royal birth in Great Britain.',
  'The earliest recorded case of a man giving up smoking was on April 5, 1679, when Johan Katsu, Sheriff of Turku, Finland, wrote in his diary "I quit smoking tobacco." He died one month later.',
  '"Goodbye" came from "God bye" which came from "God be with you."',
  'February is Black History Month.',
  'Jane Barbie was the woman who did the voice recordings for the Bell System.',
  'The first drive-in service station in the United States was opened by Gulf Oil Company - on December 1, 1913, in Pittsburgh, Pennsylvania.',
  'The elephant is the only animal with 4 knees.',
  'Kansas state law requires pedestrians crossing the highways at night to wear tail lights.',
  'Gorillas can catch human colds and other illnesses.',
  'A newborn Chinese water deer is so small it can almost be held in the palm of the hand.',
  'Ostriches can run faster than horses, and the males can roar like lions.',
  'A lion in the wild usually makes no more than twenty kills a year.',
  'The female lion does ninety percent of the hunting.',
  'The only dog that doesn\'t have a pink tongue is the chow.',
  'Turtles, water snakes, crocodiles, alligators, dolphins, whales, and other water going creatures will drown if kept underwater too long.',
  'Almost half the pigs in the world are kept by farmers in China.',
  'On average, dogs have better eyesight than humans, although not as colourful.',
  'Deer have no gall bladders.',
  'There is an average of 50,000 spiders per acre in green areas.',
  'Snakes are carnivores, which means they only eat animals, often small ones such as insects, birds, frogs and other small mammals.',
  'In Alaska it is illegal to whisper in someone\'s ear while they\'re moose hunting.',
  'The bat is the only mammal that can fly.',
  'The leg bones of a bat are so thin that no bat can walk.',
  'Some male songbirds sing more than 2000 times each day.',
  'The only mammals to undergo menopause are elephants, humpback whales and human females.',
  'The chicken and fish are the only animals that are eaten before they are born and after they die.',
  'A tarantula spider can survive for more than two years without food.',
  'For every human in the world there are one million ants.',
  'If you lift a kangaroo\'s tail off the ground it can\'t hop – they use their tails for balance.',
  'If you keep a goldfish. in a dark room, it will become pale!',
  'Cows can sleep standing up, but they can only dream lying down.',
  'The sentence “The quick brown fox jumps over a lazy dog.” uses every letter of the alphabet.',
  'The average fox weighs 14 pounds.',
  'The scientific name of the red fox is Vulpes vulpes.',
  'Alligators can live up to 100 years.',
  'A single elephant tooth can weigh as much as 9 pounds.',
  'The turkey is one of the most famous birds in North America.',
  'A housefly hums in the key of F.',
  'During World War II, Americans tried to train bats to drop bombs.',
  'Canis lupus lupus is the scientific name for a grey wolf.',
  'To escape the grip of a crocodile\'s jaw, push your thumb into its eyeballs-it will let you go instantly.',
  'It is much easier for dogs to learn spoken commands if they are given in conjunction with hand signals or gestures.',
  'Even a small amount of alcohol placed on a scorpion will make it go crazy and sting itself to death!',
  'Male rabbits are called “bucks,” females are “does.”',
  'The flamingo can only eat when its head is upside down.',
  'Animals generate 30 times more waste than humans which is 1.4 billion tons every year.',
  'Ants never sleep. Also they don\'t have lungs.',
  'A group of owls is called a parliament.',
  'Just one cow gives off enough harmful methane gas in a single day to fill around 400 litre bottles.',
  'Apple and pear seeds contain arsenic, which may be deadly to dogs.',
  'Cows have four stomachs.',
  'An anteater is nearly 6 feet long, yet its mouth is only an inch wide.',
  'The blue whale weighs as much as thirty elephants and is as long as three Greyhound buses.',
  'A herd of sixty cows is capable of producing a ton of milk in less than a day.',
  'A grasshopper can leap 20 times the length of its own body.',
  'At birth, baby kangaroos are only about an inch long – no bigger than a large water bug or a queen bee.',
  'The smell of a skunk can be detected by a human a mile away.',
  'There is a butterfly in Africa with enough poison in its body to kill six cats!',
  'Cats have lived with people for only 7,000 years.',
  'A black panther is really a black leopard.',
  'The honey bee has been around for 30 million years.',
  'The dumbest dog in the world is the Afghan hounds.',
  'A cat has 32 muscles in each ear.',
  'A dog\'s shoulder blades are unattached to the rest of the skeleton to allow greater flexibility for running.',
  'Tigers have striped skin as well as their fur.',
  'Hippos can run faster than humans!',
  'The Latin name for moose is alces alces.',
  'The earliest European images of dogs are found in cave paintings dating back 12,000 years ago in Spain.',
  'Iguanas, koalas and komodo dragons all have two penises!',
  'The kangaroo\'s ancestors lived in trees. Today there are eight different kinds of tree kangaroos.',
  'A woodpecker can peck 20 times per second.',
  'The great horned owl has no sense of smell.',
  'Scientists have performed brain surgery on cockroaches.',
  'The flea can jump up to 200 times its own height. This is equal to a man jumping the Empire State Building in New York.',
  'Most elephants weigh less than the tongue of a blue whale.',
  'The very first bomb that the Allies dropped on Berlin in World War Two hit an elephant.',
  'A garden caterpillar has 248 muscles in its head.',
  'A moth has no stomach.',
  'George Washington\'s teeth were made of elephant ivory, and walrus tusks.',
  'Reindeer milk has more fat than cow milk.',
  'Goats and sheep are seasonal breeders.',
  'An elephant can smell water up to 3 miles away.',
  'Deer can\'t eat hay.',
  'A skunk will not bite and throw its scent at the same time.',
  'In 2003, Dr. Roger Mugford invented the “wag-o-meter” a device that claims to interpret a dog\'s exact mood by measuring the wag of its tail.',
  'Every day of the year, 100 whales are killed by whale fisherman.',
  'If you cut off a snail\'s eye, it will grow a new one.',
  'The ostrich has two toes on each foot which gives it greater speed.',
  'Lonomia obliqua is the world\'s deadliest caterpillar.',
  '‘Jaws\' is the most common name for a goldfish.',
  'The most dogs ever owned by one person were 5,000 Mastiffs owned by Kubla Khan.',
  'On average, cows poop 16 times per day!',
  'The phrase “raining cats and dogs” originated in seventeenth-century England. During heavy rainstorms, many homeless animals would drown and float down the streets, giving the appearance that it had actually rained cats and dogs.',
  'The most poisonous fish in the world is the stone fish.',
  'Killer whales are not whales at all, rather a species of dolphin.',
  'Goats were the first animals domesticated by man in 10,000 B.C.',
  'Dogs have sweat glands in between their paws.',
  'The fear of animals is called zoophobia.',
  'We share 70% of our DNA with a slug.',
  'We share 98.4% of our DNA with a chimp.',
  'Fireflies do not bite or have pincers. Fireflies are harmless, they don\'t even carry diseases.',
  'Chocolate, macadamia nuts, cooked onions, or anything with caffeine is harmful to dogs.',
  'No two tigers ever have the same stripes, and this is how individual tigers can be identified.',
  'The American Kennel Club, the most influential dog club in the United States, was founded in 1884.',
  'The longest recorded life span of a slug was 1 year, 6 months.',
  'A whale\'s heart beats only nine times a minute.',
  'Elephants are covered with hair.',
  'Female koala\'s have two vagina\'s.',
  'A python can swallow a rabbit whole and may eat as many as 150 mice in a six-month period.',
  'The placement of the eyes of a donkey enables them to see all four of their legs at all times.',
  'At birth, a panda is smaller than a mouse and weighs about four ounces.',
  'Oysters can change from one gender to another and back again depending on which is best for mating.',
  'Fireflies are the only creatures that give off light without generating heat.',
  'Hummingbirds beat their wings 60 to 80 times per second.',
  'Only half of a dolphin\'s brain sleeps at a time. The other awake half makes the dolphin come up for air when needed to prevent drowning.',
  'Dogs have about 1,700 taste buds.',
  'It takes 3,000 cows to supply the NFL with enough leather for a year\'s supply of footballs.',
  'A completely blind chameleon will still take on the colours of its environment.',
  'A rodent\'s teeth never stop growing.',
  'When young abalones feed on red seaweed their shells turn red.',
  'Small quantities of grapes and raisins can cause renal failure in dogs.',
  'The hippopotamus is born underwater.',
  'Taurophobia is the fear of bulls.',
  'A bat can eat up to 1,000 insects per hour.',
  'One million stray dogs and 500,000 stray cats live in New York City metropolitan area.',
  'You can tell a turtle\'s gender by the noise it makes. Males grunt, females hiss.',
  'An elephant\'s trunk has around 15,000 muscles. 200 litres of water is drunk from it per day.',
  'The most popular female dog name is Maggie. The most popular male dog name is Max.',
  'A large group of goats is called a herd.',
  'Squirrels cannot see the colour red.',
  'The average chicken lays about 260 eggs per year.',
  'A starving mouse will eat its own tail.',
  'Only 5 to 10 percent of cheetah cubs make it to adulthood.',
  'Ferrets sleep around 20 hours a day.',
  'Birds can recognise landmarks.',
  'The starfish is the only animal capable of turning its stomach inside-out.',
  'Male dogs will raise their legs while urinating to aim higher on a tree or lamppost because they want to leave a message that they are tall and intimidating. Some wild dogs in Africa try to run up tree trunks while they are urinating to appear to be very large.',
  'Sharks have been around longer than dinosaurs.',
  'About two-thirds of shark attacks on humans have taken place in water less than six feet deep.',
  'Sharks are immune to cancer!',
  'Worldwide, more people eat and drink milk from goats than any other animal.',
  'Alligators cannot move backwards.',
  'The most popular dog breed in Canada, America, and Great Britain is the labrador retriever.',
  'The largest giant squid ever found weighed 8,000 pounds.',
  'Approximately 100 people die each year when they are stepped on by cows.',
  'A butterfly has 12,000 eyes.',
  'Humpback whales create the loudest sound of any living creature.',
  'Hippo\'s sweat is pink.',
  'Whale milk is 50% fat.',
  'In Croatia, scientists discovered that lampposts were falling down because a chemical in the urine of male dogs was rotting the metal.',
  'In the Caribbean there are oysters that can climb trees.',
  'The swan has over 25,000 feathers in its body.',
  'The blue whale is the largest of all whales and is also considered the largest animal to have ever existed in the world.',
  'Giraffes have no vocal cords.',
  'Starfish have eight eyes – one at the end of each leg.',
  'There are almost 60 million dogs in the United States.',
  'After eating, a housefly regurgitates its food and then eats it again.',
  'A mole can dig a tunnel 300 feet long in just one night.',
  'Back in 1924, a monkey was convicted in South Bend of the crime of smoking a cigarette and sentenced to pay a 25 dollar fine!',
  'Flamingos are pink because shrimp is one of their main sources of food.',
  'The Mayans and Aztecs symbolised every tenth day with the dog, and those born under this sign were believed to have outstanding leadership skills.',
  'When a male tiger and female lion mate they make a tigon, when a male lion and female tiger mate they make a liger.',
  'French poodles did not originate in France – they came from Germany.',
  'The breeding age for male goats is between 8-10 months.',
  'Elephants don\'t drink through their trunks like a straw.',
  'Baby whales grow to a 1/3 of their mother\'s length in the womb.',
  'Goats do not have teeth in their upper front jaw.',
  'Goat\'s milk is higher in calcium, vitamin A and niacin than cow\'s milk.',
  'Turkeys have a poor sense of smell, but excellent sense of taste.',
  'Cats can hear ultrasound.',
  'Tuna fish can swim 40 miles in a single day.',
  'Bumblebees have hair on their eyes.',
  'Penguins can jump 6 feet out of water.',
  'Giraffe hearts pump twice as hard as a cow\'s to get blood to its brain.',
  'Blue whales have large enough aortas (the main blood vessel) for a human to crawl through.',
  'Some dogs can smell dead bodies under water!',
  'More than 45 million turkeys are cooked and eaten in the US at Thanksgiving.',
  'Baby whales can gain up to 200 pounds per day.',
  'Dogs have a wet nose to collect more of the tiny droplets of smelling chemicals in the air.',
  'Cats have over one hundred vocal sounds, while dogs only have about ten.',
  'Cat owners are 30% less likely to suffer a heart attack.',
  'Barn owls hunt mostly small mammals such as the short-tailed vole.',
  'A ducks quack does echo, it\'s just almost impossible to hear.',
  'A cheetahs lifespan is up to 12 years in the wild.',
  'Shark corneas are being used in human eye transplants.',
  'Dogs are about as smart as a two or three-year-old child.',
  'Butterflies have their skeletons on the outside of their bodies, this is known as the exoskeleton.',
  'Arachnophobia is the fear of spiders.',
  'Polar bears are the world\'s largest land predators.',
  'Hippos attract mates by urinating and defecating.',
  'Butterflies can only see the colours red, green and yellow.',
  'Yellowtail is the general name for loads of different species of fish that have yellow tails or a yellow body.',
  'There are roughly twenty-four thousand species of butterflies.',
  'A dik-dik is a tiny antelope that lives in East Africa, Namibia and Angola.',
  'Dik-diks weigh between three and six kilogrammes.',
  'Female polar bears normally start having baby cubs at the age of four or five.',
  'Fireflies are also known as lightning bugs.',
  'Noctule bats fly before sunset, whereas Pipistrelles appear soon after sunset.',
  'In general, Asiatic jerboas have five toes on their back feet and African jerboas have three.',
  'Even though a polar bears average body temperature is 37°C; they don\'t give off any detectable heat, so they won\'t show up in infrared photographs.',
  'Dogs can see better when the light is low.',
  'Dumbledore isn\'t only the Headmaster of Hogwarts; in fact a dumbledore is an old English term for a type of bee.',
  'Most young fireflies feed on nectar and pollen, although adult fireflies do not need to eat to survive.',
  '79% of pet owners sleep with their pets.',
  'Two dogs were among the Titanic survivors.',
  'Many species of owls have special feathers for flying silently.',
  'An elephant can smell water up to 3 miles away.',
  'The animal on the Firefox logo is not a fox, but a red panda.',
  'There is only one pink bottlenose dolphin which has been discovered, in an inland lake in Louisiana, USA.',
  'China has the most goats in the world, they have over 170 Million.',
  'A chicken with red ear lobes will produce brown eggs, and a chicken with white ear lobes will produce white eggs.',
  'One survey reports that 33 percent of dog owners admit they talk to their dogs on the phone or leave messages on answering machines while they are away.',
  'The average dog can run about 19 mph.',
  'The owl has a small brain.',
  'Snakes do not blink.',
  'A squid\'s eye can get as big as a basketball.',
  'A puppy is born blind, deaf, and toothless.',
  'Agrizoophobia is the fear of wild animals.',
  'There are currently over a million animal species upon planet earth.',
  'There are over 70,000 types of spiders spinning their webs in the world.',
  'If you have a fear of chickens, then you actually have Alektorophobia.',
  'Dogs can see in colour, though they most likely see colours similar to a colour-blind human.',
  'Dogs have lived with humans for over 14,000 years.',
  'There are 3,000 kinds of lice in the world.',
  'The life of a housefly is only 14 days.',
  'The lifespan of 75% of wild birds is 6 months.',
  'Denmark has twice as many pigs as there are people.',
  'National Dance Like A Chicken Day falls on 14th May every year.',
  'The sailfish can swim at the speed of 109 km/h, making it the fastest swimmer.',
  'The crocodile\'s tongue is unmovable, as it is attached to the roof of its mouth.',
  'Greyhounds are the fastest dogs on Earth and can run at speeds of 45 mph.',
  'The Basenji is the worlds only bark-less dog.',
  'Goats are quite agile creatures and in some cases they can jump over 5 feet.',
  'In 2006, 253 fish-species were listed as critically endangered.',
  'The hippopotamus\'s skin is protected by its own pink oily secretion known as ‘pink sweat\'.',
  'The Tyrannosaurus Rex went extinct 65 million years ago.',
  'The Irish deer is the largest deer to have ever existed. It went into extinction approximately 7,700 years ago.',
  'It costs approximately $10,000 to train a federally certified search and rescue dog.',
  'The colour red doesn\'t really make bulls angry; they are color-blind.',
  'A herd of unicorns is called a blessing.',
  'The oldest recorded elephant lived for 82 years.',
  'According to records there are 50 million monkeys in the world!',
  'There are an estimated 400 million dogs in the world.',
  'Goats were the first animals to be used for milk by humans.',
  'The U.S. has the highest dog population in the world. France has the second highest.',
  'There are over 2700 types of snakes in the world and they live in deserts, forests, oceans, streams, lakes.',
  'Cows from different areas have a different moo accent.',
  'The male goat is called a “buck” or “billy”.',
  'The female goat is called a “doe” or “nanny”.',
  'A baby goat is called a “kid”.',
  'Dog nose prints are as unique as human finger prints and can be used to identify them.',
  'Ailurophobia is the fear of cats.',
  'Ichthyophobia is the fear of fish.',
  'Female bald eagles are 25% larger than males.',
  'Frogs don\'t drink water. They absorb water through their skin.',
  'Suriphobia is the fear of mice.',
  'There are over 210 breeds of goats in the world.',
  'A polar bear\'s outer fur is called ‘guard hair\'.',
  'An adult lion\'s roar is so loud; it can be heard up to five miles away.',
  'There is a shark called ‘goblin shark\' which has only been seen around 50 times since its discovery in 1897.',
  'There are approximately 450 million goats around the world.',
  'Dalmatians are completely white at birth.',
  'A beaver\'s teeth never stop growing.',
  'Apiphobia is the fear of bees.',
  'The average dolphin eats one-third of its weight on food each day.',
  'Goats and octopus\' pupils of their eyes are rectangular.',
  'African elephants only have four teeth to chew their food with.',
  'The scales of a crocodile are made of certain, the same substance that hooves and fingernails are made of.',
  'Crocodiles eat stones.',
  'Crocodiles have brains no larger than a cigar.',
  'Cheetahs were trained by man for hunting as long as 3000 BC.',
  'Horses can\'t vomit.',
  'Both male and female caribou grow antlers.',
  'Alternate American names for the Elk are the moose and the Wapiti.',
  'A group of frogs is called an army.',
  'Tigers can see 6 times better at night than humans.',
  'Starfish don\'t die of old age.',
  'A male gorilla can eat 40 pounds of food a day.',
  'A group of whales is called a pod.',
  'Female harp seals get in groups to have their babies one mating season is over.',
  'When giraffes age, their fur darkens.',
  'Heron\'s eggs have a greenish-blue pale colour.',
  'You are more likely to be killed by a champagne cork than by a poisonous spider.',
  'All dolphins have a different whistle.',
  'Scientists had to go 45 million years back in history to find the elephant\'s oldest ancestor.',
  'Tiger Day is the last Sunday in September.',
  'There is no visual difference between male and female herons.',
  'A full-grown bear can run as fast as a horse.',
  'Hyenas regularly eat the faeces of other animals.',
  'Frogs cannot swallow without blinking.',
  'A giraffe has the same number of bones in its neck as a man.',
  'Moose have very poor vision. Some have even tried to mate with cars.',
  'The swan has over 25,000 feathers on its body.',
  'African elephants have bigger ears than Indian elephants.',
  'There is no record of a human being attacked by a healthy wolf.',
  'Hummingbirds are the only birds who can fly backwards.',
  'Dolphins can eat up to 30 pounds of fish a day.',
  'There\'s a spider in Brazil whose bites can cause an erection that lasts for hours!',
  'There are no ants in Iceland, Greenland, and Antarctica.',
  'Before they\'re even born, sand tiger sharks eat their twin brothers and sisters!',
  'Jellyfish evaporate in the sun. They\'re 98% water.',
  'Rooster is simply a male chicken.',
  'Pikachu is a mouse type Pokémon.',
  'Some lions mate over 50 times a day.',
  'The Big Five is a group of animals of Africa: cape buffalo, elephant, leopard, lion and rhino.',
  'The slowest fish is the sea horse, which moves along at about 0.01 mph (0.016 km/h).',
  'Millions of trees are accidentally planted by squirrels that bury nuts and then forget where they hid them.',
  'The lifespan of a bush baby is 14 years.',
  'A survey showed 29 per cent of adults say they have been splashed or scalded by hot drinks while dunking biscuits.',
  'Ortharexia Nervosa is an eating disorder where the sufferer is obsessed with eating healthy food.',
  'Ketchup was sold in the 1830s as medicine.',
  'Dry swallowing one teaspoon of sugar can commonly cure hic-ups.',
  'In Kentucky, it is illegal to carry an ice cream cone in your back pocket.',
  'The fear of cooking is known as Mageirocophobia and is a recognised phobia.',
  'The tea bag was introduced in 1908 by Thomas Sullivan of New York.',
  'The tall chef\'s hat is called a toque.',
  'Arachibutyrophobia is the fear of peanut butter sticking to the roof of the mouth.',
  'In South Africa, termites and ants are often roasted and eaten by the handful, like popcorn.',
  'Every time you lick a stamp, you consume 1/10 of a calorie.',
  'Pearls melt in vinegar.',
  'The \'57\' on the Heinz ketchup bottle represents the number of pickle types the company once had.',
  'Marmite was first introduced into the UK in 1902.',
  'The ancient Greeks chewed a gum-like substance called mastic that came from the bark of a tree.',
  'Honeybee workers must visit 2 million flowers to make one pound of honey.',
  'The fear of vegetables is called Lachanophobia.',
  'Almonds are a member of the peach family.',
  'If you boil beetroot in water, and then massage the water into your scalp each night, it works as an effective cure for dandruff.',
  'In the United States, lettuce is the second most popular fresh vegetable.',
  'Grape growing is the largest food industry in the world as there are more than 60 species and 8000 varieties of grapes.',
  'The average person eats eight pounds of grapes each year.',
  'There are more than 7,000 varieties of apples grown in the world.',
  'A cluster of bananas id formerly called a ‘hand\'. Along that theme, a single banana is called a ‘finger\'.',
  'Onion is Latin for ‘large pearl\'.',
  'Apples, pears, cherries and strawberries are all members of the rose family.',
  'The word vegetable has no scientific definition, so it\'s still acceptable to call a tomato a vegetable.',
  'In the Philippines, it is considered good luck if a coconut is cleanly split open without jagged edges.',
  'When cranberries are ripe, they bounce like a rubber ball.',
  'The most amount of grapes eaten in 3 minutes is 133. This record was set in 2001 by Mat Hand, from the UK.',
  'There are more than 10,000 varieties of tomatoes.',
  'In 2001, there were more than 300 banana-related accidents in Britain, most involving people slipping on skins.',
  'If you want to speed up the ripening of a pineapple, so that you can eat it faster, then you can do it by standing it upside down (on the leafy end).',
  'Carrots have zero fat content.',
  'Peanuts can be used to make dynamite.',
  'A watermelon is over 92% water by weight.',
  'Alliumphobia is the fear of garlic.',
  'A row of corn always has an even number.',
  'The pumpkin originated in Mexico about 9,000 years ago.',
  'Square watermelons sell for about $85.',
  'Turnips are high in fibre, Vitamin C, Calcium and Potassium.',
  'Eating a lot of beetroot turns your pee into a pink colour.',
  'Biting a wooden spoon whilst chopping an onion will stop your eyes from watering.',
  'Each pineapple plant only produces just one pineapple per year.',
  'Lettuce is a member of the sunflower family.',
  'Blueberries are a good source of Vitamin C and fibre.',
  'Pumpkin flowers are edible.',
  'Peaches are the third most popular fruit grown in America.',
  'We are eating 900% more broccoli than we did 20 years ago.',
  'There are more than 600 pasta shapes produced worldwide.',
  'Geomelophagia is someone who has the urge to eat raw potatoes.',
  '9th August is officially National Rice Pudding Day.',
  'Rice can be used in beer, dog food, baby food, breakfast cereals, snacks, frozen foods and sauces!',
  'October is National Pasta Month.',
  'Canadian neurosurgeon Dr. Wilder Penfield, while operating on epilepsy patients, discovered the ‘Toast Centre\' of the human brain, which is wholly dedicated to detecting when toast is burning!',
  '16 billion jelly beans are made for Easter. stacked end to end, the jelly beans would circle the globe nearly 3 times!',
  'Before 1991 Twix Bars were internationally knows as ‘Raider\'.',
  'The Arabs invented caramel.',
  'Before Walkers owned Wotsits, they sold a rival known as Cheetos on the UK market.',
  'Pringles were first sold in America in 1968 but were not popular until the mid 1970\'s.',
  'Saddam Hussein liked Bounty Bars!',
  'Frank Mars invented the Snickers chocolate bar. He named it Snickers after his favourite horse.',
  'The M\'s in M & M\'s stand for ‘Mars & Murrie\', the co-creators of the candy.',
  'Twinkies originally had banana flavoured filling, but switched to vanilla when World War 2 bought the banana trade to a halt.',
  'Cadbury\'s Cream Eggs first went on sale in 1971.',
  'In 2006, Shari\'s Berries pioneered the concept of delivering chocolate dipped fruits nationwide in freeze packs.',
  'The Kit Kat was originally made by Rowntree Limited, until 1988 when they were bought out by Nestle.',
  'Juicy Fruit and Wrigley\'s Spearmint gums are more than 100 years old!',
  'Hundreds and Thousands (Sprinkles, Nonpareils, Jimmies) are small round balls of brightly coloured sugar used as decorations on cakes, cookies, trifles and other desserts. Their use dates back at least to the early 19th century.',
  'Gummy Bears are only 79 millimetres long in length.',
  'Chocolate can kill dogs; it directly affects their heart and nervous system.',
  'Deep fried chocolate bars contain about 850 calories per bar.',
  'The world\'s oldest chocolates are 106 years old. A tin of chocolates from the coronation of King Edward VII from 1902.',
  'Yorkie Chocolate Bars are not for girls!',
  'Sugar is the only taste that humans are born craving.',
  'The Swiss eat the most chocolate, followed by the English.',
  'The Bourbon biscuit was introduced in 1910 originally under the name Creola.',
  'In 15th century France, chocolate could only be eaten by members of the royal court.',
  'Gorgonzola cheese dates back to the year 879!',
  'Many mass-produced ice creams have seaweed in them.',
  'Cheese products contain less than 51% cheese.',
  'Some yoghurt contain beef or pork gelatin.',
  'The weight of a Babybel is 21 grammes.',
  'An average American will eat the equivalent of 28 pigs in their lifetime.',
  'National Pigs-in-a-Blanket Day is celebrated on 24th April every year.',
  'The first soup was made from hippopotamus and dates back to 6000 B.C.',
  'Baked beans are low in fat and have a lot of fibre and protein.',
  'Worcestershire sauce is made from dissolved fish.',
  'Pescetarians are vegetarians who eat fish.',
  'The largest item on any menu in the world is the roast camel.',
  'Egg yolks are one of the few foods that naturally contain Vitamin D.',
  'The average hot dog is consumed in 6 bites.',
  'Until well into the sixteenth century, bacon was a Middle English term used to refer to all pork in general.',
  'In America, anchovies always rank last on the list of favourite toppings.',
  'The world average of the amount of meat eaten per year is: 173 lbs per person.',
  'French fries came from Belgium, but are most popular in the US.',
  'An average person will consume 12 pubic hairs in their fast food every year!',
  'KFC (Kentucky Fried Chicken) was founded by Colonel Harland Sanders in 1952.',
  'We eat 300 million portions of fish and chips in Britain each year.',
  'Chicken McNuggets contain beef additives.'
]

export default class Facts extends React.Component {

  constructor() {
    super(...arguments);

    this.state = {index: 0};
  }

  handleClick(e) {

    this.setState({index: (this.state.index+1) % facts.length });
  }

  componentWillUnmount() {
    window.removeEventListener('click', this.handleClick.bind(this));
  }

  componentWillMount() {

    window.addEventListener('click', this.handleClick.bind(this));
  }

  render() {
    return (
      <div className="fact">
        {facts[this.state.index]}
      </div>
    );
  }
}
